//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class anh
    {
        public int imageID { get; set; }
        public string path { get; set; }
        public Nullable<int> ServiceID { get; set; }
    
        public virtual dichvu dichvu { get; set; }
    }
}
